### PR TITLE
vaUSDC: Exit from fuse#18

### PR DESCRIPTION
**Pull request by patidarmanoj10**

### CODE REVIEW

**Comment by jcvernaleo** [comment]
Making the vaUSDC changes now since that does not require new deploy.

**Comment by virendrapatidar** [comment]
@patidarmanoj10 , @jcvernaleo 

- Rebalance done for vaUSDC pool and fund is deployed to Convex4 strategy.  
- rebalance done for veWBTC-DAI pool for Maker strategy, tiny fund in the pool. There is no `vaWBTC` strategy linked with veWBTC-DAI.

**Review by jcvernaleo — APPROVED** [review]
OK

**Review by green-jeff — COMMENTED** [review]
ok

**Pull request merged**
