### PR TITLE
Update weight of Convex and Compound leverage strategy in vaWBTC pool

### PR DESCRIPTION
**Pull request by patidarmanoj10**
Low APY in Convex. Reduce weight to 0.  WBTC is potential candidate for leveraging in Compound. Borrow APY is  ~ -2%. After leveraging up to 3 level, expected APY from compound is 2.4%.  Lets gradually increase compound leverage strategy weigh. Starting with 5%. 
**Current weights**

|Strategy | Weight |
|-------: | --------|
|Convex | 15%     |
|Yearn| 0%     |
|Maker-vaDAI | 70%   | 
|Rari fuse pool#23 | 9%     |
|Compound Leverage | 0%     |
|Pool buffer | 6%     |

**Change this to** 

|Strategy | Weight |
|-------: | --------|
|Convex | 0%     |
|Yearn| 0%     |
|Maker-vaDAI | 81%   | 
|Rari fuse pool#23 | 9%     |
|Compound Leverage | 5%     |
|Pool buffer | 5%     |

### CODE REVIEW

**Review by gabmontes — COMMENTED** [review]
LGTM

**Comment by patidarmanoj10** [comment]
Pool is vaWBTC

**Comment by patidarmanoj10** [comment]
Updated weight table. Added Compound leverage strategy. This will need new strategy contract deployment.

**Review by virendrapatidar — APPROVED** [review]

**Review by jgarzik — APPROVED** [review]

**Review by rokso — APPROVED** [review]

**Comment by green-jeff** [comment]
@patidarmanoj10 did we implement this? I still see weight on Convex per internal dashboard

**Comment by patidarmanoj10** [comment]
@green-jeff No. Compound leverage has low APY lately so let's not add Compound leverage. Update proposal is 


|Strategy | Weight |
|-------: | --------|
|Convex | 0%     |
|Yearn| 0%     |
|Maker-vaDAI | 86%   | 
|Rari fuse pool#23 | 9%     |
|Pool buffer | 5%     |

**Comment by jcvernaleo** [comment]
New set of values look good to me

**Review by jcvernaleo — APPROVED** [review]
OK

**Pull request merged**
