### PR TITLE
Set 0 weight of strategy#23

### PR DESCRIPTION
**Pull request by patidarmanoj10**
Set 0 weight for strategy#23

### CODE REVIEW

**Comment by patidarmanoj10** [comment]
@virendrapatidar Once this is updated,  call rebalance of #23 to withdraw 100% and then call rebalance of other strategy.

**Comment by virendrapatidar** [comment]
@patidarmanoj10 , 
You mean setting weight 0 for vaDAI pool for strategy#23 ?
The [PR](https://github.com/vesperfi/vesper-pool-ops/pull/23) is linked with vaALUSD and we don't have any strategy#23 for  vaALUSD.

**Comment by virendrapatidar** [comment]
@patidarmanoj10, Sure I will keep a watch on this.

**Review by jgarzik — APPROVED** [review]

**Review by jcvernaleo — APPROVED** [review]
OK

**Comment by jcvernaleo** [comment]
Changes done.

**Comment by virendrapatidar** [comment]
Rebalance is done.
First rebalance #23 and then Vesper-Maker-Strategy-ETH with 95% weight.

**Pull request merged**
