### PR TITLE
Deploy vaETH to Pool #8, Inverse leverage

### PR DESCRIPTION
**Pull request by green-jeff**
Exit alpha homora, deploy 25% to pool #8 and 30% to inverse leverage, rest to maker vaDAI

Until inverse leverage passes due diligence, absorb that weight into maker strategy

### CODE REVIEW

**Comment by jcvernaleo** [comment]
@patidarmanoj10 we don't have rarifuse 8 deployed here.  Can I just migrate rarifuse 23 to that?  It has 0 weight currently.

**Comment by patidarmanoj10** [comment]
Yes. we can migrate 23

**Review by patidarmanoj10 — APPROVED** [review]

**Review by jcvernaleo — APPROVED** [review]
OK

**Comment by jcvernaleo** [comment]
All changes made

**Pull request merged**
