### PR TITLE
Update weights for vaWBTC

### PR DESCRIPTION
**Pull request by jcvernaleo**
adds compound leverage strategy

### CODE REVIEW

**Comment by jcvernaleo** [comment]
This matches the way things are currently set.

**Comment by patidarmanoj10** [comment]
@jcvernaleo I tested compound leverage strategy. it looks good. Proposed weight. 

|Curve| 0%     |
|Curve Convex| 40%     |
|Rari fuse pool#23 | 9%     |
|Maker WBTC-C | 0%    |
|Compound Leverage | 46% |
|Pool buffer | 5%     |

**Comment by jcvernaleo** [comment]
New weights looks good to me.  I will update PR (and then update actual weights).

**Review by patidarmanoj10 — APPROVED** [review]

**Comment by jcvernaleo** [comment]
Weight changes done and now match this PR.

**Pull request merged**
