### PR TITLE
Rebalance vaETH Weights

### PR DESCRIPTION
**Pull request by green-jeff**
Increase Maker-vaDAI weight to 90%, decrease Fuse 23 to 5%

### CODE REVIEW

**Comment by patidarmanoj10** [comment]
@green-jeff  cc @jgarzik @jcvernaleo Change in pool 23 weight will impact available liquidity in Rari .  This will need review . and assess impact of it.

**Comment by patidarmanoj10** [comment]
LGTM. No change require in strategy#23 in contract. its already 6%.

**Review by patidarmanoj10 — APPROVED** [review]

**Review by jcvernaleo — APPROVED** [review]
OK

**Comment by jcvernaleo** [comment]
Done.

**Pull request merged**
