### PR TITLE
Increase weight of convex strategy

### PR DESCRIPTION
**Pull request by patidarmanoj10**
Gradually increasing weight of convex strategy

### CODE REVIEW

**Comment by patidarmanoj10** [comment]
@virendrapatidar once this is updated, can you rebalance strategy which weight reduce and then do convex . Make sure proportional fund move other strategies to convex

**Comment by virendrapatidar** [comment]
@patidarmanoj10 , Sure I will take create of that.

**Review by virendrapatidar — APPROVED** [review]

**Review by jgarzik — APPROVED** [review]

**Review by jcvernaleo — APPROVED** [review]
OK

**Comment by jcvernaleo** [comment]
Changes made.

**Comment by virendrapatidar** [comment]
Txn submitted for Rari fuse pool#7 and Rari fuse pool#18 strategies (weight reduced). it's pending due to high gas.

Once the above two strategies txns are completed, will call rebalance of Convex4 FRAXPool strategy.

**Comment by virendrapatidar** [comment]
Rebalanced Convex4 FRAXPool strategy for vaDAI pool.

**Pull request merged**
