### PR TITLE
Update weight in Avalanche pools

### PR DESCRIPTION
**Pull request by patidarmanoj10**

### CODE REVIEW

**Comment by patidarmanoj10** [comment]
@green-jeff cc @jcvernaleo Okay set all weight to Joe

**Review by jcvernaleo — APPROVED** [review]
Looks good to me.

OK

**Comment by patidarmanoj10** [comment]
This PR also include exit from Convex strategy in vaWBTC pool.

**Review by jcvernaleo — APPROVED** [review]
OK

**Comment by jcvernaleo** [comment]
Making the changes now.

**Comment by jcvernaleo** [comment]
vaAVAX is the only one not done yet because for some reason that transaction is taking a very long time (something I see on avalanche occasionally).

**Comment by jcvernaleo** [comment]
All updates done.

**Pull request merged**
