### PR TITLE
Increase weight of Compound leverage

### PR DESCRIPTION
**Pull request by patidarmanoj10**
ETH has very good leverage opportunity in Compound. Increase weight of Compound leverage.

### CODE REVIEW

**Review by jcvernaleo — APPROVED** [review]
Looks good.

**Comment by patidarmanoj10** [comment]
@jcvernaleo Let's hold on this.  We may want one more round of review before this update.

**Comment by jcvernaleo** [comment]
Does #85 make this one obsolete?  @patidarmanoj10 @green-jeff

**Comment by patidarmanoj10** [comment]
Yes

**Pull request closed without merging**
