### PR TITLE
vaDAI weight update

### PR DESCRIPTION
**Pull request by patidarmanoj10**
Proposed changes for vaDAI pool
|Strategy | Weight |
|-------: | --------|
|Convex | 0%     |
|Yearn| 0%     |
|Rari fuse pool#6 | 20%     |
|Rari fuse pool#7 | 20%     |
|Rari fuse pool#8 | 20%     |
|Rari fuse pool#18 | 20%     |
|Rari fuse pool#23 | 10%     |
|Pool buffer | 5%     |

### CODE REVIEW

**Review by jgarzik — APPROVED** [review]

**Review by jcvernaleo — APPROVED** [review]
Looks good.

**Review by green-jeff — APPROVED** [review]

**Review by green-jeff — CHANGES_REQUESTED** [review]
Recommended weights:

Rari Fuse #6: 30%
Rari Fuse #7: 20%
Rari Fuse #8: 10%
Rari Fuse #18: 30%
Rari Fuse #23: 5%
Pool Buffer: 5%

**Comment by patidarmanoj10** [comment]
@green-jeff @jcvernaleo I recommend following. 

Rari Fuse #6: 30%
Rari Fuse #7: 20%
Rari Fuse #8: 0%
Rari Fuse #18: 33%
Rari Fuse #23: 12% (no change)
Pool Buffer: 5%

**Review by jcvernaleo — APPROVED** [review]
I'm good with those weights.

**Comment by patidarmanoj10** [comment]
Ignore previous recommendation. Just reviewed everything again and below will result in better
Rari Fuse #6: 30%
Rari Fuse #7: 15%
Rari Fuse #8: 10%
Rari Fuse #18: 30%
Rari Fuse #23: 12% (no change)
Pool Buffer: 3%

**Review by jcvernaleo — APPROVED** [review]
OK

**Comment by jcvernaleo** [comment]
OK was to the proposed values in the most recent comment.  PR still has old numbers i think.

**Review by jgarzik — APPROVED** [review]

**Comment by jcvernaleo** [comment]
Weights have been updated to match the values here:
https://etherscan.io/tx/0x189d5d10257920bdaec79e0cb6197c32c2142ff92a259c26ca8d284e44884c2a
https://etherscan.io/tx/0x94734965db8094e72287f3b6987ca16d3c46e78cd0fd1e5be8be7fc95c34fb96

**Pull request merged**
